#!/bin/sh

if [ "$TRIPPI_HOME" = "" ]; then
  TRIPPI_HOME=.
fi
if [ ! -f "$TRIPPI_HOME/lib/trippi-0.9.jar" ]; then
  echo "ERROR: When running trippi from a directory other than where it was"
  echo "       installed, you must define the TRIPPI_HOME environment variable"
  echo "       to be the directory where it was installed."
  exit 1
fi
(exec java -Xms64m -Xmx96m -Djava.endorsed.dirs="$TRIPPI_HOME/lib" -Dtrippi.home="$TRIPPI_HOME" $1 $2 $3 $4 $5 $6 $7 $8 $9)
exit 0
